config/routes.rb
Antigona::Application.routes.draw do
  devise_for :users

  resources :publicacions
  resources :posts
  resources :fotos
  resources :integrantes
  resources :textos

  get "main/inicio"
  get "main/experiencias"
  get "main/que_hacemos"
  match "/admin" => "main#panel_control"
  get "main/panel_control"
  get "main/contacto"

  root :to => 'main#inicio'

end

app/controllers/main_controller.rb
class MainController < ApplicationController
  before_filter :authenticate_user!, only: [:panel_control]


  def inicio
  end
  def experiencias
  end
  def que_hacemos
  end
  def panel_control
    unless current_user.admin?
      flash[:error] = "no eres administrador"
      redirect_to root_url
    end
  end
  def contacto
  end

end

app/helpers/main_helper.rb
module MainHelper
  def getTexto(clave)
    if Texto.find_by_name(clave)
      then Texto.find_by_name(clave).content
    else
       flash[:error] = "ERROR: no se ha encontrado el texto"
    end

  end
end

app/views/main/contacto.html.haml
.bloque_dir_prin
  %address
    %h3 Antígona Procesos Participativos
  %p C/ Cea Bermúdez 14 3º - 3
  %p 28003 Madrid
  %p Tlf. / Fax: 91-5350319
  %p
    %a{:href => "mailto:asociacion@antigona.org.es"} asociacion@antigona.org.es
  %br
.bloque_dir.clearfix
  %address
    %h4 En Madrid
    %p Luz Buitrago
    %p Concha Lorenzana
    %p
      %a{:href => "mailto:lbuitrago@antigona.org.es"} lbuitrago@antigona.org.es
    %p
      %a{:href => "mailto:clorenzana@antigona.org.es"} clorenzana@antigona.org.es
    %br
.bloque_dir
  %address
    %h4 En Córdoba
    %p Ernesto Ganuza
    %p
      %a{:href => "mailto:eganuza@antigona.org.es"} eganuza@antigona.org.es
    %br
.bloque_dir
  %address
    %h4 En Barcelona
    %p Lucrecia Olivari
    %p Pablo Paño
    %p
      %a{:href => "mailto:lolivari@antigona.org.es"} lolivari@antigona.org.es
    %p
      %a{:href => "mailto:pablopano@antigona.org.es"} pablopano@antigona.org.es
    %br

app/views/main/experiencias.html.haml
%iframe{:frameborder => "0", :height => "600px", :width => "90%", :marginheight => "0", :marginwidth => "0", :scrolling => "no", :src => "http://meipi.org/experiencias.meipi.php"}

app/views/main/inicio.html.haml
%header
  %section.cuerpo#principal
    %h1 Antígona
    %article
      %h2 Procesos participativos
      %strong#texto-principal
        %p= getTexto("que_hacemos")
    %article
      .container-fluid#fotos
        %p
        - @fotos.each do |foto|
          .span3
            = image_tag(foto.img_link , class: "img-rounded", id: "fotoportada")

app/views/main/panel_control.html.haml
%header
  %section.cuerpo
    .hero-unit#titulo
      %h1 Panel de control
    %article
      %h2 Bienvenido al panel de control
      %p Desde aquí podrá editar el contenido de la web, pulse en los distintos aparatados para desplegarlos y ver las opciones
    %article
      .seccion
        %h3
          %a Integrantes de la organización
        .listado#apartado
          %ul
            - @integrantes.each do |integrante|
              .bloque
                %li
                  %a
                    %strong=integrante.name
                .contenido
                  %p= integrante.description.html_safe
                  %p= button_to 'Editar', edit_integrante_path(integrante), method: "get", class: "btn btn-primary"
          %p= button_to 'Nuevo integrante', new_integrante_path(), method: "get", class: "btn btn-primary"
      .seccion
        %h3
          %a Publicaciones:
        .listado#apartado
          %ul
            - @publicaciones.each do |publicacion|
              .bloque
                %li
                  %a
                    %strong= publicacion.name
                .contenido
                  %p= publicacion.description.html_safe
                  %p= button_to 'Editar', edit_publicacion_path(publicacion), method: "get", class: "btn btn-primary"
          %p= button_to 'Nueva publicación', new_publicacion_path(), method: "get", class: "btn btn-primary"
      .seccion
        %h3
          %a Fotos del carrusel:
        .listado#apartado
          %ul
            - @fotos.each do |foto|
              .bloque
                %li
                  %a
                    %strong= foto.name
                .contenido
                  %p= foto.img_link
                  %p
                    -unless foto.img_link == ""
                      = image_tag foto.img_link, :size => "200x200", class: "img-rounded"

                  %p= button_to 'Editar', edit_foto_path(foto), method: "get", class: "btn btn-primary"
          %p= button_to 'Nueva foto', new_foto_path(), method: "get", class: "btn btn-primary"
      .seccion
        %h3
          %a Post del blog:
        .listado#apartado
          %ul
            - @posts.each do |post|
              .bloque
                %li
                  %a
                    %strong= post.title
                .contenido
                  %p
                    -unless post.img_link == ""
                      = image_tag post.img_link, :size => "200x200", class: "img-rounded"
                  %p= post.description.html_safe
                  %p= button_to 'Editar', edit_post_path(post), method: "get", class: "btn btn-primary"
          %p= button_to 'Nuevo post', new_post_path(), method: "get", class: "btn btn-primary"
      .seccion
        %h3
          %a Textos de la web:
        .listado#apartado
          %ul
            - @textos.each do |texto|
              .bloque
                %li
                  %a
                    %strong= texto.name
                  .contenido
                    %p= texto.content
                    %p= button_to 'Editar', edit_texto_path(texto), method: "get", class: "btn btn-primary"

app/views/main/que_hacemos.html.haml
%header
  %section.cuerpo
    %h1 Antigona
    %article
      %h2 ¿Qué hacemos?
    %article
      %p#texto-principal
        = getTexto("que_hacemos")