config/routes.rb
Antigona::Application.routes.draw do
  devise_for :users

  resources :publicacions
  resources :posts
  resources :fotos
  resources :integrantes
  resources :textos

  get "main/inicio"
  get "main/experiencias"
  get "main/que_hacemos"
  match "/admin" => "main#panel_control"
  get "main/panel_control"
  get "main/contacto"

  root :to => 'main#inicio'

end

app/models/integrante.rb
class Integrante < ActiveRecord::Base
  attr_accessible :cv_link, :description, :img_link, :name, :pos
end

app/controllers/integrantes_controller.rb
class IntegrantesController < ApplicationController
  before_filter :authenticate_user!, except: [:show, :index]
  # GET /integrantes
  # GET /integrantes.json
  def index
    @integrantes = Integrante.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @integrantes }
    end
  end

  # GET /integrantes/1
  # GET /integrantes/1.json
  def show
    @integrante = Integrante.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @integrante }
    end
  end

  # GET /integrantes/new
  # GET /integrantes/new.json
  def new
    @integrante = Integrante.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @integrante }
    end
  end

  # GET /integrantes/1/edit
  def edit
    @integrante = Integrante.find(params[:id])
  end

  # POST /integrantes
  # POST /integrantes.json
  def create
    @integrante = Integrante.new(params[:integrante])

    respond_to do |format|
      if @integrante.save
        format.html { redirect_to @integrante, notice: 'Integrante was successfully created.' }
        format.json { render json: @integrante, status: :created, location: @integrante }
      else
        format.html { render action: "new" }
        format.json { render json: @integrante.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /integrantes/1
  # PUT /integrantes/1.json
  def update
    @integrante = Integrante.find(params[:id])

    respond_to do |format|
      if @integrante.update_attributes(params[:integrante])
        format.html { redirect_to @integrante, notice: 'Integrante was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @integrante.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /integrantes/1
  # DELETE /integrantes/1.json
  def destroy
    @integrante = Integrante.find(params[:id])
    @integrante.destroy

    respond_to do |format|
      format.html { redirect_to integrantes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/integrantes_helper.rb
module IntegrantesHelper
end

app/views/integrantes/_form.html.erb
<%= form_for @integrante, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= cktext_area :integrante, :description, :ckeditor => {:uiColor => "#dddddd", :toolbar => "mini"} %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :cv_link, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :cv_link, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :img_link, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :img_link, :class => 'text_field' %>
      <% unless @integrante.img_link == "" %>
           <%= image_tag @integrante.img_link, :size => "100x100", class: "img-rounded", id: "foto_derecha" %>
      <% end %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :pos, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :pos, :class => 'number_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                integrantes_path, :class => 'btn' %>
  </div>
<% end %>

app/views/integrantes/edit.html.erb
<%- model_class = Integrante -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/integrantes/index.html.haml
%h1#titulo ¿Quiénes somos?
%p#texto-principal
  = getTexto("quienes_somos")
  %table.table.table-striped.table-bordered.table-hover
    %thead
      %tr
        %th Nuestros integrantes son:
    %tbody
    - @integrantes.each do |int|
      %tr
        %td= image_tag(int.img_link, class: "foto_persona")
        %td= link_to int.name, integrante_path(int)
        %td= truncate(int.description.html_safe, length: 800)
        %td= link_to "Curriculum vitae", int.cv_link

app/views/integrantes/new.html.erb
<%- model_class = Integrante -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/integrantes/show.html.haml
%h1
  = link_to @integrante.name, integrante_path(@integrante)
%p
  - unless @integrante.img_link == ""
    = image_tag @integrante.img_link, :size => "200x200", class: "img-rounded", id: "foto-integrante"
  %p= @integrante.description.html_safe
  %p= link_to "link al curriculum", @integrante.cv_link
  = l @integrante.created_at