config/routes.rb
Antigona::Application.routes.draw do
  devise_for :users

  resources :publicacions
  resources :posts
  resources :fotos
  resources :integrantes
  resources :textos

  get "main/inicio"
  get "main/experiencias"
  get "main/que_hacemos"
  match "/admin" => "main#panel_control"
  get "main/panel_control"
  get "main/contacto"

  root :to => 'main#inicio'

end

app/models/foto.rb
class Foto < ActiveRecord::Base
  attr_accessible :img_link, :name, :section
end

app/controllers/fotos_controller.rb
class FotosController < ApplicationController
  before_filter :authenticate_user!, except: [:show, :index]
  # GET /fotos
  # GET /fotos.json
  def index
    @fotos = Foto.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @fotos }
    end
  end

  # GET /fotos/1
  # GET /fotos/1.json
  def show
    @foto = Foto.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @foto }
    end
  end

  # GET /fotos/new
  # GET /fotos/new.json
  def new
    @foto = Foto.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @foto }
    end
  end

  # GET /fotos/1/edit
  def edit
    @foto = Foto.find(params[:id])
  end

  # POST /fotos
  # POST /fotos.json
  def create
    @foto = Foto.new(params[:foto])

    respond_to do |format|
      if @foto.save
        format.html { redirect_to @foto, notice: 'Foto was successfully created.' }
        format.json { render json: @foto, status: :created, location: @foto }
      else
        format.html { render action: "new" }
        format.json { render json: @foto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /fotos/1
  # PUT /fotos/1.json
  def update
    @foto = Foto.find(params[:id])

    respond_to do |format|
      if @foto.update_attributes(params[:foto])
        format.html { redirect_to @foto, notice: 'Foto was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @foto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fotos/1
  # DELETE /fotos/1.json
  def destroy
    @foto = Foto.find(params[:id])
    @foto.destroy

    respond_to do |format|
      format.html { redirect_to fotos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/fotos_helper.rb
module FotosHelper
end

app/views/fotos/_form.html.erb
<%= form_for @foto, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :img_link, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :img_link, :class => 'text_field' %>
      <% unless @foto.img_link == "" %>
        <%= image_tag @foto.img_link, :size => "200x200", class: "img-rounded", id: "foto_derecha" %>
      <% end %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :section, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :section, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                fotos_path, :class => 'btn' %>
  </div>
<% end %>

app/views/fotos/edit.html.erb
<%- model_class = Foto -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/fotos/index.html.erb
<%- model_class = Foto -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:img_link) %></th>
      <th><%= model_class.human_attribute_name(:section) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @fotos.each do |foto| %>
      <tr>
        <td><%= link_to foto.id, foto_path(foto) %></td>
        <td><%= foto.name %></td>
        <td><%= foto.img_link %></td>
        <td><%= foto.section %></td>
        <td><%=l foto.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_foto_path(foto), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      foto_path(foto),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_foto_path,
            :class => 'btn btn-primary' %>

app/views/fotos/new.html.erb
<%- model_class = Foto -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/fotos/show.html.erb
<%- model_class = Foto -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @foto.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:img_link) %>:</strong></dt>
  <dd><%= @foto.img_link %></dd>
  <dt><strong><%= model_class.human_attribute_name(:section) %>:</strong></dt>
  <dd><%= @foto.section %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              fotos_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_foto_path(@foto), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              foto_path(@foto),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>