config/routes.rb
Antigona::Application.routes.draw do
  devise_for :users

  resources :publicacions
  resources :posts
  resources :fotos
  resources :integrantes
  resources :textos

  get "main/inicio"
  get "main/experiencias"
  get "main/que_hacemos"
  match "/admin" => "main#panel_control"
  get "main/panel_control"
  get "main/contacto"

  root :to => 'main#inicio'

end

app/views/layouts/_footer.html.haml
.contenedor-pie
  .pie
    %ul#lista-pie
      %li
        %h5 GALERÍA MULTIMEDIA
        %HR/
      %li= link_to "Enlace a Flickr", "http://www.flickr.com/photos/antigonapparticipativos"
      %li= link_to "Enlace a Vimeo", "https://vimeo.com/asociacionantigona/videos"
      %li= link_to "Enlace a Meipi", "http://meipi.org/experiencias.meipi.php"
    %ul#lista-pie
      %li
        %h5 ENTRADAS RECIENTES
        %HR/
        - @ultimos_posts.each do |post|
          %li= link_to post.title, post
    %ul#lista-pie
      %li
        %h5 CONTACTANOS
        %HR/
      %li= link_to "C/ Cea Bermúdez 14 3º - 3-28003 Madrid", main_contacto_path
      %li= link_to "Tlf. / Fax: 91-5350319", main_contacto_path
      %li= mail_to "asociacion@antigona.org.es"

  %p &copy; Pepetox 2013

app/views/layouts/_header.html.haml
.logo
  %a#logo{:href => root_url}= image_tag("logo_antigona.jpg", id: "logo")
.navbar.navbar-fluid-top
  .navbar-inner
    .container-fluid
      %a.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse"}

      .container-fluid.nav-collapse
        %ul.nav.center
          %li.barra= link_to "¿QUÉ HACEMOS?", main_que_hacemos_path
          %li.barra= link_to "¿QUIÉNES SOMOS?", integrantes_path
          %li.barra= link_to "EXPERIENCIAS", main_experiencias_path
          %li.barra= link_to "PUBLICACIONES", publicacions_path
          %li.barra= link_to "BLOG", posts_path
          %li.barra= link_to "CONTACTO", main_contacto_path
          / %li.barra
          /   =link_to "Panel de control", admin_path
          / %li.barra
          /   - if user_signed_in?
          /     = link_to "Desconectarse", destroy_user_session_path, :method => :delete
        / /.nav-collapse

app/views/layouts/_navbar.html.haml
.well.sidebar-nav
  %ul.nav.nav-list
    %li.nav-header Barra de navegación
    %li.dropdown
      %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
        Publicaciones
        %b.caret
      %ul.dropdown-menu
        - @publicaciones.each do |publicacion|
          %li= link_to publicacion.name, publicacion
    %li.dropdown
      %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
        Integrantes
        %b.caret
      %ul.dropdown-menu
        - @integrantes.each do |integrante|
          %li= link_to integrante.name, integrante
    %li
      =link_to "Panel de control", admin_path
    %li
      - if user_signed_in?
        = link_to "Desconectarse", destroy_user_session_path, :method => :delete

app/views/layouts/application.html.haml
!!!
%html{:lang => "es"}
  %head
    %meta{:charset => "utf-8"}
      %meta{:content => "IE=Edge,chrome=1", "http-equiv" => "X-UA-Compatible"}
        %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
          %title= content_for?(:title) ? yield(:title) : "Antigona"
          = csrf_meta_tags
          = javascript_include_tag "application"
          / Le HTML5 shim, for IE6-8 support of HTML elements
          /[if lt IE 9]
            <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
            <link href='http://fonts.googleapis.com/css?family=Caudex' rel='stylesheet' type='text/css'>
          = stylesheet_link_tag "application", :media => "all"
          / For third-generation iPad with high-resolution Retina display:
          / Size should be 144 x 144 pixels
          = favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
          / For iPhone with high-resolution Retina display:
          / Size should be 114 x 114 pixels
          = favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
          / For first- and second-generation iPad:
          / Size should be 72 x 72 pixels
          = favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
          / For non-Retina iPhone, iPod Touch, and Android 2.1+ devices:
          / Size should be 57 x 57 pixels
          = favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
          / For all other devices
          / Size should be 32 x 32 pixels
          = favicon_link_tag 'antifav.ico', :rel => 'shortcut icon'
  %body


    = render 'layouts/header'
    .container-fluid
      .row-fluid#centrar
        .span8
          = bootstrap_flash
          = yield
      / /row
      = render 'layouts/footer'

    / /container
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster